"""add constraints indexes and field lengths

Revision ID: c631b9144e7e
Revises: 022a3aaa1668
Create Date: 2026-04-09 09:44:38.858622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c631b9144e7e'
down_revision: Union[str, None] = '022a3aaa1668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_animal_status', 'animals', ['status'], unique=False)
    op.create_index('ix_death_reported_by', 'death_records', ['reported_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_death_reported_by', table_name='death_records')
    op.drop_index('ix_animal_status', table_name='animals')
    # ### end Alembic commands ###
